# -*- coding: utf-8 -*-
"""Story Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXt0s7nQwJGpMwWOx_g1ea-xdSUadfeu
"""

pip install transformers

from transformers import pipeline

# Load a small pre-trained model
generator = pipeline("text-generation", model="gpt2")

# Try generating text
output = generator("My name is pookie", max_length=30, num_return_sequences=1)
print(output[0]['generated_text'])